import { effect, Injectable, signal } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  currentLanguage = signal(localStorage.getItem('language') || 'en');

  private translations: any = {
    en: {
      movies: 'Movies',
      tvShows: 'TV Shows',
      popular: 'Popular',
      trending: 'Trending',
      popularShowsMovies: 'Popular Shows & Movies',
      nowPlaying: 'Now Playing',
      upcoming: 'Upcoming',
      topRated: 'Top Rated',
      airingToday: 'Airing Today',
      onTv: 'On TV',
      home: 'Home',
      wishlist: 'Wish List',
      login: 'Log in',
      signup: 'Sign Up',
      account: 'Account Details',
      logout: 'Logout',
      search: 'Search',
      searchAndExplore: 'Search and explore...',
      searchResults: 'Search Results',
      today: 'Today',
      thisWeek: 'This Week',
      welcomeTitle: 'Welcome to our movie app',
      welcomeSubtitle: 'Millions of movies, TV shows and people to discover. Explore now.',
      companyName: 'ACME Industries Ltd.',
      companySlogan: 'Providing reliable tech since 1992',
      social: 'Social',
      watchlist: 'Watch List',
      noMoviesInWatchlist: 'No movies in watch list',
      ourTeam: 'Our Team',
      dontHaveAccount: "Don't have an account?",
      passwordMustBeAtLeast6: 'Password must be at least 6 characters',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      enterYourEmail: 'Enter Your Email',
      email: 'Email',
      showPassword: 'Show password',
      name: 'Name',
      accountExists: 'This Account Exists',
      passwordNotMatch: 'Password Not Match',
    },

    ar: {
      movies: 'الأفلام',
      tvShows: 'المسلسلات',
      popular: 'الأكثر شهرة',
      trending: 'الرائج الآن',
      popularShowsMovies: 'العروض والأفلام الرائجة',
      nowPlaying: 'يعرض الآن',
      upcoming: 'القادمة',
      topRated: 'الأعلى تقييمًا',
      airingToday: 'يُعرض اليوم',
      onTv: 'على التلفاز',
      home: 'الرئيسية',
      wishlist: 'قائمة المفضلة',
      login: 'تسجيل الدخول',
      signup: 'إنشاء حساب',
      account: 'تفاصيل الحساب',
      logout: 'تسجيل الخروج',
      search: 'بحث',
      searchAndExplore: 'ابحث واستكشف...',
      searchResults: 'نتائج البحث',
      today: 'اليوم',
      thisWeek: 'هذا الأسبوع',
      welcomeTitle: 'مرحبًا بك في تطبيق الأفلام الخاص بنا',
      welcomeSubtitle: 'ملايين الأفلام والعروض التلفزيونية والأشخاص لاكتشافهم. استكشف الآن.',
      companyName: 'شركة أكمي للصناعات المحدودة',
      companySlogan: 'نقدم تقنيات موثوقة منذ عام 1992',
      social: 'وسائل التواصل الاجتماعي',
      watchlist: 'قائمة المشاهدة',
      noMoviesInWatchlist: 'لا توجد أفلام في قائمة المشاهدة',
      ourTeam: 'فريقنا',
      dontHaveAccount: 'ليس لديك حساب؟',
      passwordMustBeAtLeast6: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      enterYourEmail: 'أدخل بريدك الإلكتروني',
      email: 'البريد الإلكتروني',
      showPassword: 'عرض كلمة المرور',
      name: 'الاسم',
      accountExists: 'هذا الحساب موجود',
      passwordNotMatch: 'كلمة المرور غير متطابقة',
    },

    fr: {
      movies: 'Films',
      tvShows: 'Séries TV',
      popular: 'Populaire',
      trending: 'Tendance',
      popularShowsMovies: 'Émissions et films populaires',
      nowPlaying: 'En Salle',
      upcoming: 'À Venir',
      topRated: 'Les Mieux Notés',
      airingToday: "Diffusé Aujourd'hui",
      onTv: 'À la Télé',
      home: 'Accueil',
      wishlist: 'Liste de Souhaits',
      login: 'Connexion',
      signup: "S'inscrire",
      account: 'Détails du Compte',
      logout: 'Se Déconnecter',
      search: 'Rechercher',
      searchAndExplore: 'Rechercher et explorer...',
      searchResults: 'Résultats de recherche',
      today: "Aujourd'hui",
      thisWeek: 'Cette semaine',
      welcomeTitle: 'Bienvenue sur notre application de films',
      welcomeSubtitle:
        'Des millions de films, séries et personnes à découvrir. Explorez maintenant.',
      companyName: 'ACME Industries Ltd.',
      companySlogan: 'Fournir une technologie fiable depuis 1992',
      social: 'Réseaux sociaux',
      watchlist: 'Liste à regarder',
      noMoviesInWatchlist: 'Aucun film dans la liste à regarder',
      ourTeam: 'Notre équipe',
      dontHaveAccount: "Vous n'avez pas de compte ?",
      passwordMustBeAtLeast6: 'Le mot de passe doit contenir au moins 6 caractères',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      enterYourEmail: 'Entrez votre email',
      email: 'Email',
      showPassword: 'Afficher le mot de passe',
      name: 'Nom',
      accountExists: 'Ce compte existe',
      passwordNotMatch: 'Le mot de passe ne correspond pas',
    },

    zh: {
      movies: '电影',
      tvShows: '电视剧',
      popular: '热门',
      trending: '趋势',
      popularShowsMovies: '热门节目和电影',
      nowPlaying: '正在上映',
      upcoming: '即将上映',
      topRated: '高评分',
      airingToday: '今日播出',
      onTv: '电视上',
      home: '主页',
      wishlist: '愿望清单',
      login: '登录',
      signup: '注册',
      account: '账户详情',
      logout: '登出',
      search: '搜索',
      searchAndExplore: '搜索与探索...',
      searchResults: '搜索结果',
      today: '今天',
      thisWeek: '本周',
      welcomeTitle: '欢迎来到我们的电影应用',
      welcomeSubtitle: '数百万部电影、电视剧和人物等你探索。立即开始吧。',
      companyName: 'ACME 工业有限公司',
      companySlogan: '自 1992 年以来提供可靠的技术',
      social: '社交',
      watchlist: '观看列表',
      noMoviesInWatchlist: '观看列表中没有电影',
      ourTeam: '我们的团队',
      dontHaveAccount: '没有账户？',
      passwordMustBeAtLeast6: '密码必须至少6个字符',
      password: '密码',
      confirmPassword: '确认密码',
      enterYourEmail: '输入您的邮箱',
      email: '邮箱',
      showPassword: '显示密码',
      name: '姓名',
      accountExists: '该账户已存在',
      passwordNotMatch: '密码不匹配',
    },
  };
  constructor() {
    effect(() => {
      const lang = this.currentLanguage();
      document.dir = lang === 'ar' ? 'rtl' : 'ltr';
      localStorage.setItem('language', lang);
    });
  }
  setLanguage(lang: string) {
    this.currentLanguage.set(lang);
  }
  t(key: string): string {
    const lang = this.currentLanguage();
    return this.translations[lang][key] || key;
  }
}
